#ifndef _N80DEV_CONFIG_H
#define _N80DEV_CONFIG_H

#define BMP_USE_BITMAP2
// #define BMP_USE_OR_BITMAP
#define BMP_USE_FILL_RECT
// #define BMP_USE_INVERT_RECT
// #define BMP_USE_DRAW_PATLINES

// #define FNT_USE_SFONT

// #define BGM_USE_NOTE

#define PUSH_KEYS (KEY_2|KEY_4|KEY_6|KEY_8|KEY_X|KEY_Z|KEY_SPACE|KEY_RET)
#define PUSH_FUNC_KEYS (KEY_SHIFT)

#endif // !_N80DEV_CONFIG_H
